trigger:
  branches:
    include:
      - main

variables:
  imageName: 'azure-devops-sginalr'

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - script: dotnet build --configuration Release
            displayName: 'Build project'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/bin/Release'
              artifactName: 'drop'

  - stage: Containerize
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: '$(imageName)'
              dockerfile: '**/Dockerfile'
              containerRegistry: 'youracr.azurecr.io'
              tags: |
                $(Build.BuildId)
              
  - stage: Deploy
    jobs:
      - job: DeployToAppService
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'AKS'
              appName: 'azure-devops-sginalr'
              imageName: 'miniprojectregistry.azurecr.io/$(azure-devops-sginalr):$(Build.BuildId)'
