apiVersion: v1
kind: Service
metadata:
  name: signalr-chat-service
  labels:
    app: signalr-chat
spec:
  selector:
    app: signalr-chat
  ports:
    - protocol: TCP
      port: 80           # The port exposed to the outside world
      targetPort: 80      # The port inside the container where the app is listening
  type: LoadBalancer    # Expose the service with a LoadBalancer (for external access)
